/*
 * The MIT License (MIT)
 *
 * Copyright (c) 2007-2026 Daniel Alievsky, AlgART Laboratory (http://algart.net)
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

package net.algart.arrays.demo;

import net.algart.arrays.Arrays;
import net.algart.arrays.JArrays;

import java.util.Collection;
import java.util.List;
import java.util.Locale;
import java.util.Set;

/**
 * <p>Test for <code>Arrays.toString</code> and <code>JArrays.toString</code> methods.</p>
 *
 * @author Daniel Alievsky
 */
public class ArraysToStringTest {
    public static void test(String separator, int maxStringLength) {
        String s;
        //[[Repeat() boolean   ==> char,,byte,,short,,int,,long,,float,,double,,Object;;
        //           Objects   ==> objects,,...;;
        //           false ==> 0,,...;;
        //           true ==> 23,,...]]
        boolean[] booleans = {false, true};
        s = JArrays.toString(booleans, separator, maxStringLength);
        System.out.printf("booleans[%d]: \"%s\"%n", booleans.length, s);
        if (!s.equals(Arrays.toString(Arrays.SMM.of(booleans), separator, maxStringLength))) {
            throw new AssertionError();
        }
        booleans = new boolean[0];
        s = JArrays.toString(booleans, separator, maxStringLength);
        System.out.printf("booleans[%d]: \"%s\"%n", booleans.length, s);
        if (!s.equals(Arrays.toString(Arrays.SMM.of(booleans), separator, maxStringLength))) {
            throw new AssertionError();
        }
        booleans = new boolean[100];
        s = JArrays.toString(booleans, separator, maxStringLength);
        System.out.printf("booleans[%d]: \"%s\"%n", booleans.length, s);
        if (!s.equals(Arrays.toString(Arrays.SMM.of(booleans), separator, maxStringLength))) {
            throw new AssertionError();
        }

        //[[Repeat.AutoGeneratedStart !! Auto-generated: NOT EDIT !! ]]
        char[] chars = {0, 23};
        s = JArrays.toString(chars, separator, maxStringLength);
        System.out.printf("chars[%d]: \"%s\"%n", chars.length, s);
        if (!s.equals(Arrays.toString(Arrays.SMM.of(chars), separator, maxStringLength))) {
            throw new AssertionError();
        }
        chars = new char[0];
        s = JArrays.toString(chars, separator, maxStringLength);
        System.out.printf("chars[%d]: \"%s\"%n", chars.length, s);
        if (!s.equals(Arrays.toString(Arrays.SMM.of(chars), separator, maxStringLength))) {
            throw new AssertionError();
        }
        chars = new char[100];
        s = JArrays.toString(chars, separator, maxStringLength);
        System.out.printf("chars[%d]: \"%s\"%n", chars.length, s);
        if (!s.equals(Arrays.toString(Arrays.SMM.of(chars), separator, maxStringLength))) {
            throw new AssertionError();
        }

        byte[] bytes = {0, 23};
        s = JArrays.toString(bytes, separator, maxStringLength);
        System.out.printf("bytes[%d]: \"%s\"%n", bytes.length, s);
        if (!s.equals(Arrays.toString(Arrays.SMM.of(bytes), separator, maxStringLength))) {
            throw new AssertionError();
        }
        bytes = new byte[0];
        s = JArrays.toString(bytes, separator, maxStringLength);
        System.out.printf("bytes[%d]: \"%s\"%n", bytes.length, s);
        if (!s.equals(Arrays.toString(Arrays.SMM.of(bytes), separator, maxStringLength))) {
            throw new AssertionError();
        }
        bytes = new byte[100];
        s = JArrays.toString(bytes, separator, maxStringLength);
        System.out.printf("bytes[%d]: \"%s\"%n", bytes.length, s);
        if (!s.equals(Arrays.toString(Arrays.SMM.of(bytes), separator, maxStringLength))) {
            throw new AssertionError();
        }

        short[] shorts = {0, 23};
        s = JArrays.toString(shorts, separator, maxStringLength);
        System.out.printf("shorts[%d]: \"%s\"%n", shorts.length, s);
        if (!s.equals(Arrays.toString(Arrays.SMM.of(shorts), separator, maxStringLength))) {
            throw new AssertionError();
        }
        shorts = new short[0];
        s = JArrays.toString(shorts, separator, maxStringLength);
        System.out.printf("shorts[%d]: \"%s\"%n", shorts.length, s);
        if (!s.equals(Arrays.toString(Arrays.SMM.of(shorts), separator, maxStringLength))) {
            throw new AssertionError();
        }
        shorts = new short[100];
        s = JArrays.toString(shorts, separator, maxStringLength);
        System.out.printf("shorts[%d]: \"%s\"%n", shorts.length, s);
        if (!s.equals(Arrays.toString(Arrays.SMM.of(shorts), separator, maxStringLength))) {
            throw new AssertionError();
        }

        int[] ints = {0, 23};
        s = JArrays.toString(ints, separator, maxStringLength);
        System.out.printf("ints[%d]: \"%s\"%n", ints.length, s);
        if (!s.equals(Arrays.toString(Arrays.SMM.of(ints), separator, maxStringLength))) {
            throw new AssertionError();
        }
        ints = new int[0];
        s = JArrays.toString(ints, separator, maxStringLength);
        System.out.printf("ints[%d]: \"%s\"%n", ints.length, s);
        if (!s.equals(Arrays.toString(Arrays.SMM.of(ints), separator, maxStringLength))) {
            throw new AssertionError();
        }
        ints = new int[100];
        s = JArrays.toString(ints, separator, maxStringLength);
        System.out.printf("ints[%d]: \"%s\"%n", ints.length, s);
        if (!s.equals(Arrays.toString(Arrays.SMM.of(ints), separator, maxStringLength))) {
            throw new AssertionError();
        }

        long[] longs = {0, 23};
        s = JArrays.toString(longs, separator, maxStringLength);
        System.out.printf("longs[%d]: \"%s\"%n", longs.length, s);
        if (!s.equals(Arrays.toString(Arrays.SMM.of(longs), separator, maxStringLength))) {
            throw new AssertionError();
        }
        longs = new long[0];
        s = JArrays.toString(longs, separator, maxStringLength);
        System.out.printf("longs[%d]: \"%s\"%n", longs.length, s);
        if (!s.equals(Arrays.toString(Arrays.SMM.of(longs), separator, maxStringLength))) {
            throw new AssertionError();
        }
        longs = new long[100];
        s = JArrays.toString(longs, separator, maxStringLength);
        System.out.printf("longs[%d]: \"%s\"%n", longs.length, s);
        if (!s.equals(Arrays.toString(Arrays.SMM.of(longs), separator, maxStringLength))) {
            throw new AssertionError();
        }

        float[] floats = {0, 23};
        s = JArrays.toString(floats, separator, maxStringLength);
        System.out.printf("floats[%d]: \"%s\"%n", floats.length, s);
        if (!s.equals(Arrays.toString(Arrays.SMM.of(floats), separator, maxStringLength))) {
            throw new AssertionError();
        }
        floats = new float[0];
        s = JArrays.toString(floats, separator, maxStringLength);
        System.out.printf("floats[%d]: \"%s\"%n", floats.length, s);
        if (!s.equals(Arrays.toString(Arrays.SMM.of(floats), separator, maxStringLength))) {
            throw new AssertionError();
        }
        floats = new float[100];
        s = JArrays.toString(floats, separator, maxStringLength);
        System.out.printf("floats[%d]: \"%s\"%n", floats.length, s);
        if (!s.equals(Arrays.toString(Arrays.SMM.of(floats), separator, maxStringLength))) {
            throw new AssertionError();
        }

        double[] doubles = {0, 23};
        s = JArrays.toString(doubles, separator, maxStringLength);
        System.out.printf("doubles[%d]: \"%s\"%n", doubles.length, s);
        if (!s.equals(Arrays.toString(Arrays.SMM.of(doubles), separator, maxStringLength))) {
            throw new AssertionError();
        }
        doubles = new double[0];
        s = JArrays.toString(doubles, separator, maxStringLength);
        System.out.printf("doubles[%d]: \"%s\"%n", doubles.length, s);
        if (!s.equals(Arrays.toString(Arrays.SMM.of(doubles), separator, maxStringLength))) {
            throw new AssertionError();
        }
        doubles = new double[100];
        s = JArrays.toString(doubles, separator, maxStringLength);
        System.out.printf("doubles[%d]: \"%s\"%n", doubles.length, s);
        if (!s.equals(Arrays.toString(Arrays.SMM.of(doubles), separator, maxStringLength))) {
            throw new AssertionError();
        }

        Object[] objects = {0, 23};
        s = JArrays.toString(objects, separator, maxStringLength);
        System.out.printf("objects[%d]: \"%s\"%n", objects.length, s);
        if (!s.equals(Arrays.toString(Arrays.SMM.of(objects), separator, maxStringLength))) {
            throw new AssertionError();
        }
        objects = new Object[0];
        s = JArrays.toString(objects, separator, maxStringLength);
        System.out.printf("objects[%d]: \"%s\"%n", objects.length, s);
        if (!s.equals(Arrays.toString(Arrays.SMM.of(objects), separator, maxStringLength))) {
            throw new AssertionError();
        }
        objects = new Object[100];
        s = JArrays.toString(objects, separator, maxStringLength);
        System.out.printf("objects[%d]: \"%s\"%n", objects.length, s);
        if (!s.equals(Arrays.toString(Arrays.SMM.of(objects), separator, maxStringLength))) {
            throw new AssertionError();
        }

        //[[Repeat.AutoGeneratedEnd]]
        booleans = new boolean[]{false, false, true, true, true};
        s = JArrays.toBinaryString(booleans, separator, maxStringLength);
        System.out.printf("booleans[%d] (binary): \"%s\"%n", booleans.length, s);
        if (!s.equals(Arrays.toHexString(Arrays.SMM.of(booleans), separator, maxStringLength))) {
            throw new AssertionError();
        }

        ints = new int[]{-1, 14, 2352};
        s = JArrays.toHexString(ints, separator, maxStringLength);
        System.out.printf("ints[%d] (hex): \"%s\"%n", ints.length, s);
        if (!s.equals(Arrays.toHexString(Arrays.SMM.of(ints), separator, maxStringLength))) {
            throw new AssertionError();
        }

        chars = new char[]{33, 65336, 'z'};
        s = JArrays.toHexString(chars, separator, maxStringLength);
        System.out.printf("chars[%d] (hex): \"%s\"%n", chars.length, s);
        if (!s.equals(Arrays.toHexString(Arrays.SMM.of(chars), separator, maxStringLength))) {
            throw new AssertionError();
        }

        floats = new float[]{-1, 2223.3412f, 123456.3f};
        s = JArrays.toString(floats, Locale.US, "%.3f", separator, maxStringLength);
        System.out.printf("floats[%d] (formatter): \"%s\"%n", floats.length, s);
        if (!s.equals(Arrays.toString(Arrays.SMM.of(floats), Locale.US, "%.3f", separator, maxStringLength))) {
            throw new AssertionError();
        }

        Collection<String> list = List.of("Hello1", "Hello2", "");
        s = JArrays.toString(list, String::toUpperCase, separator, maxStringLength);
        System.out.printf("list[%d] (formatted): \"%s\"%n", list.size(), s);
        s = JArrays.toString(list, separator, maxStringLength);
        System.out.printf("list[%d]: \"%s\"%n", list.size(), s);
        if (!s.equals(Arrays.toString(Arrays.SMM.of(list.toArray()), separator, maxStringLength))) {
            throw new AssertionError();
        }
        list = Set.of();
        s = JArrays.toString(list, separator, maxStringLength);
        //noinspection ConstantValue
        System.out.printf("list[%d]: \"%s\"%n", list.size(), s);
        if (!s.equals(Arrays.toString(Arrays.SMM.of(list.toArray()), separator, maxStringLength))) {
            throw new AssertionError();
        }
        list = Arrays.asList(Arrays.nObjectCopies(97,"My"));
        s = JArrays.toString(list, separator, maxStringLength);
        System.out.printf("list[%d]: \"%s\"%n", list.size(), s);
        if (!s.equals(Arrays.toString(Arrays.SMM.of(list.toArray()), separator, maxStringLength))) {
            throw new AssertionError();
        }
        System.out.println();
    }

    public static void main(String[] args) {
        test(", ", 1);
        test("", 20);
        test(";", 100);
    }
}
