/*
 * The MIT License (MIT)
 *
 * Copyright (c) 2007-2026 Daniel Alievsky, AlgART Laboratory (http://algart.net)
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

package net.algart.arrays.demo;

import net.algart.arrays.Arrays;
import net.algart.arrays.JArrays;
import net.algart.arrays.Matrix;
import net.algart.arrays.UpdatablePArray;

public class ArrayJADemo {
    @SuppressWarnings("ImplicitArrayToString")
    public static void main(String[] args) {
        if (args.length < 2) {
            System.out.println("Usage: " + ArrayJADemo.class.getName()
                    + " elementType arrayLength");
            return;
        }
        String elementType = args[0];
        int arrayLength = Integer.parseInt(args[1]);
        UpdatablePArray array = (UpdatablePArray) Arrays.SMM.newUnresizableArray(
                DemoUtils.elementType(elementType),
                arrayLength);
        Matrix<UpdatablePArray> matrix = Matrix.as(array, arrayLength, 1);
        final double scale = matrix.maxPossibleValue(1000.0);
        for (long p = 0; p < arrayLength; p++) {
            array.setDouble(p, scale * p / (double) arrayLength);
        }

        System.out.println(array + ": " + Arrays.toString(array, ", ", 160));
        System.out.println(matrix);
        Object a = array.ja();
        System.out.println("Java array: " + a);
        if (matrix.elementType() != boolean.class && matrix.ja() != a) throw new AssertionError();
        //[[Repeat() byte ==> short,,int,,long,,float,,double;;
        //           Byte ==> Short,,Int,,Long,,Float,,Double]]
        byte[] bytes = array.jaByte();
        if (!java.util.Arrays.equals(bytes, matrix.jaByte())) throw new AssertionError();
        System.out.println("bytes: " + bytes + ", " + JArrays.toString(bytes, ", ", 160));
        bytes = array.toByte(new byte[arrayLength + 2]);
        System.out.println("larger: " + bytes + ", " + JArrays.toString(bytes, ", ", 160));
        //[[Repeat.AutoGeneratedStart !! Auto-generated: NOT EDIT !! ]]
        short[] shorts = array.jaShort();
        if (!java.util.Arrays.equals(shorts, matrix.jaShort())) throw new AssertionError();
        System.out.println("shorts: " + shorts + ", " + JArrays.toString(shorts, ", ", 160));
        shorts = array.toShort(new short[arrayLength + 2]);
        System.out.println("larger: " + shorts + ", " + JArrays.toString(shorts, ", ", 160));
        int[] ints = array.jaInt();
        if (!java.util.Arrays.equals(ints, matrix.jaInt())) throw new AssertionError();
        System.out.println("ints: " + ints + ", " + JArrays.toString(ints, ", ", 160));
        ints = array.toInt(new int[arrayLength + 2]);
        System.out.println("larger: " + ints + ", " + JArrays.toString(ints, ", ", 160));
        long[] longs = array.jaLong();
        if (!java.util.Arrays.equals(longs, matrix.jaLong())) throw new AssertionError();
        System.out.println("longs: " + longs + ", " + JArrays.toString(longs, ", ", 160));
        longs = array.toLong(new long[arrayLength + 2]);
        System.out.println("larger: " + longs + ", " + JArrays.toString(longs, ", ", 160));
        float[] floats = array.jaFloat();
        if (!java.util.Arrays.equals(floats, matrix.jaFloat())) throw new AssertionError();
        System.out.println("floats: " + floats + ", " + JArrays.toString(floats, ", ", 160));
        floats = array.toFloat(new float[arrayLength + 2]);
        System.out.println("larger: " + floats + ", " + JArrays.toString(floats, ", ", 160));
        double[] doubles = array.jaDouble();
        if (!java.util.Arrays.equals(doubles, matrix.jaDouble())) throw new AssertionError();
        System.out.println("doubles: " + doubles + ", " + JArrays.toString(doubles, ", ", 160));
        doubles = array.toDouble(new double[arrayLength + 2]);
        System.out.println("larger: " + doubles + ", " + JArrays.toString(doubles, ", ", 160));
        //[[Repeat.AutoGeneratedEnd]]
        boolean[] booleans = array.toBoolean();
        System.out.println("booleans: " + booleans + ", " +
                JArrays.toString(booleans, ", ", 160));
        if (booleans.length != array.length()) throw new AssertionError();
        for (int i = 0; i < array.length(); i++) {
            if (booleans[i] != (array.getDouble(i) != 0.0)) throw new AssertionError();
        }
    }
}
